export const VISIBLE_RADIUS_M = 500
export const UNLOCK_RADIUS_M = 50
export const UNLOCK_ACCURACY_M = 50
export const FETCH_RADIUS_M = 1000
export const RECON_RADIUS_M = 2000
export const RECON_CLUSTER_M = 80
export const RECON_RECENTER_M = 40
export const HEADING_SMOOTH = 0.28
export const FOV_HALF_DEG = 30
export const MERGE_RADIUS_M = 40
export const REFETCH_MOVE_M = 150
export const WIKI_LIMITS = [50, 100, 250, 500] as const
export const DEFAULT_WIKI_LIMIT = 50
export const WIKI_MAX_LIMIT = 500
export const RECON_BEAM_COLOR = '#e2473a'
export const POINTS_UNLOCK = 10
export const POINTS_READ = 5
export const APP_NAME = 'FactHunter'
